# Generated by Django 4.0.3 on 2022-07-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='age',
            field=models.CharField(max_length=100),
        ),
    ]
