# Generated by Django 4.0.3 on 2022-07-02 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resume_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='age',
        ),
    ]
