# Generated by Django 4.0.3 on 2022-07-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_resume_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='doc',
            field=models.FileField(blank=True, upload_to='documents'),
        ),
    ]
